In [39]:
import tensorflow as tf
import numpy as np

# Explicitly name them

In [30]:
import tensorflow as tf
a = tf.constant(2, name="a")
b = tf.constant(3, name="b")
x = tf.add(a, b, name="add")
writer = tf.summary.FileWriter("/tmp/graphs", sess.graph)
with tf.Session() as sess:
    print sess.run(x) # >> 5

5


# Tensors filled with a specific value

In [35]:
# tf.zeros(shape, dtype=tf.float32, name=None)
# creates a tensor of shape and all elements will be zeros (when ran in session)
tf.zeros([2, 3], tf.int32) # ==> [[0, 0, 0], [0, 0, 0]]

# tf.zeros_like(input_tensor, dtype=None, name=None, optimize=True)
# creates a tensor of shape and type (unless type is specified) as the input_tensor but all elements are zeros
input_tensor = [[0, 1], [2, 3], [4, 5]]
tf.zeros_like(input_tensor) # ==> [[0, 0], [0, 0], [0, 0]]

# tf.ones(shape, dtype=tf.float32, name=None)
tf.ones_like(input_tensor, dtype=None, name=None, optimize=True)

# tf.fill(dims, value, name=None)
#creates a tensor filled with a scalar value.
tf.fill([2, 3], 8) # ==> [[8, 8, 8], [8, 8, 8]]

<tf.Tensor 'Fill:0' shape=(2, 3) dtype=int32>

# TensorFlow Data Types

In [37]:
# TensorFlow takes Python natives types: boolean, numeric (int, float), strings
# 0-d tensor, or "scalar"
t_0 = 19
tf.zeros_like(t_0) # ==> 0
tf.ones_like(t_0) # ==> 1

# 1-d tensor, or "vector"
t_1 = ['apple', 'peach', 'banana']
tf.zeros_like(t_1) # ==> ['' '' '']
# tf.ones_like(t_1) # ==> TypeError: Expected string, got 1 of type 'int' instead.

# 2x2 tensor, or "matrix"
t_2 = [[True, False, False],
 [False, False, True],
 [False, True, False]]
tf.zeros_like(t_2) # ==> 2x2 tensor, all elements are False
tf.ones_like(t_2) # ==> 2x2 tensor, all elements are True


<tf.Tensor 'ones_like_4:0' shape=(3, 3) dtype=bool>

# TF vs NP Data Types

In [40]:
# TensorFlow integrates seamlessly with NumPy
tf.int32 == np.int32 # True

# Can pass numpy types to TensorFlow ops
tf.ones([2, 2], np.float32) # ⇒ [[1.0 1.0], [1.0 1.0]]

# For tf.Session.run(fetches):
# If the requested fetch is a Tensor , then the output of will be a NumPy ndarray.

<tf.Tensor 'ones:0' shape=(2, 2) dtype=float32>

## Do not use Python native types for tensors because TensorFlow has to infer Python type 

## Constants are stored in the graph definition 

# Print out the graph def

In [41]:
import tensorflow as tf
my_const = tf.constant([1.0, 2.0], name="my_const")
with tf.Session() as sess:
    print sess.graph.as_graph_def()
# you will see value of my_const stored in the graph’s definition

node {
  name: "truncated_normal/shape"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
          dim {
            size: 2
          }
        }
        tensor_content: "\274\002\000\000\n\000\000\000"
      }
    }
  }
}
node {
  name: "truncated_normal/mean"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
        }
        float_val: 0.0
      }
    }
  }
}
node {
  name: "truncated_normal/stddev"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
        }
        float_val: 1.0
      }
    }
  }
}
node {
  name: "truncated_normal/TruncatedNormal"
  op: "TruncatedNormal"
  input: "trunca

## This makes loading graphs expensive when constants are big 

## Only use constants for primitive types. Use variables or readers for more data that requires more memory

# Variables

In [42]:
# create variable a with scalar value
a = tf.Variable(2, name="scalar")
# create variable b as a vector
b = tf.Variable([2, 3], name="vector")
# create variable c as a 2x2 matrix
c = tf.Variable([[0, 1], [2, 3]], name="matrix")
# create variable W as 784 x 10 tensor, filled with zeros
W = tf.Variable(tf.zeros([784,10]))

# Why tf.constant but tf.Variable and not tf.variable? 
# tf.Variable is a class, but tf.constant is an op

# initialize variables

In [43]:
W = tf.Variable(tf.truncated_normal([700, 10]))
with tf.Session() as sess:
    sess.run(W.initializer)
    print W

<tf.Variable 'Variable_11:0' shape=(700, 10) dtype=float32_ref>


# eval a Variable

In [44]:
W = tf.Variable(tf.truncated_normal([3,5]))
with tf.Session() as sess:
    sess.run(W.initializer)
    print W.eval()

[[-0.79247504  0.58842736 -0.08192753  1.54205322 -1.00851297]
 [-0.32575756  1.75994849  0.10817643 -1.21396101  1.82847893]
 [-1.00304079  0.41854221 -0.09950946  0.11488612  0.07235698]]


# assign should become effective

In [45]:
W = tf.Variable(10)
W.assign(100)
with tf.Session() as sess:
    sess.run(W.initializer)
    print W.eval()

10


In [46]:
W = tf.Variable(10)
assign_op = W.assign(100)
with tf.Session() as sess:
    sess.run(assign_op)
    print W.eval()

100


In [47]:
my_var = tf.Variable(2, name='my_var')
my_var_two = my_var.assign(2 * my_var)
with tf.Session() as sess:
    sess.run(my_var.initializer)
    print my_var.eval()
    sess.run(my_var_two)
    print my_var_two.eval()
    sess.run(my_var_two)
    print my_var_two.eval()

2
8
32


# assign_add() and assign_sub()

In [48]:
my_var = tf.Variable(10)
with tf.Session() as sess:
    sess.run(my_var.initializer)
    print my_var.eval()
    sess.run(my_var.assign_add(10))
    print my_var.eval()
    sess.run(my_var.assign_sub(2))
    print my_var.eval()

10
20
18


# Each session maintains its own copy of variable

In [49]:
my_var = tf.Variable(10)
sess1 = tf.Session()
sess2 = tf.Session()

sess1.run(my_var.initializer)
sess2.run(my_var.initializer)

print sess1.run(my_var.assign_add(10))
print sess2.run(my_var.assign_sub(2))


print sess1.run(my_var.assign_add(100))
print sess2.run(my_var.assign_sub(50))


20
8
120
-42


# Use a variable to initialize another variable

In [50]:
# to declare U = W * 2
W = tf.Variable(tf.truncated_normal([7, 10]))
U = tf.Variable(W.initialized_value() * 2)
# insure W is initializer before it's value is used to initialize U
with tf.Session() as sess:
    sess.run(W.initializer)
    print W.eval()
    sess.run(U.initializer)
    print U.eval()

[[-0.14871779 -0.247201    0.74910808 -1.72483206  1.01080668  0.92223477
   1.5458678  -0.46298099  1.00254667 -1.10179496]
 [ 0.07078572  1.26535392  0.24387832 -1.04685378 -0.00823343  0.68652791
  -0.13281128 -0.25051695 -0.3226268  -0.74804705]
 [ 0.80371433 -0.87622875 -1.89086664  1.48425853 -1.69263983  1.444368
   0.22374426 -0.39879394 -0.51960611 -0.48616812]
 [-0.37178826 -1.0671941   0.97136956  1.188218    0.65721017  0.94243306
  -0.55476218  1.56785309 -1.09860206  0.07634071]
 [ 1.23224306 -1.10307431 -0.30122352  0.62502432  0.14632021 -1.13595748
   0.03637702 -0.53702682 -0.00223989 -0.07207614]
 [ 0.41251385 -0.18875428 -0.57382184 -1.35699368  1.1914773  -0.69786215
  -0.39543501 -0.30958903  0.42005712 -0.7246998 ]
 [-0.15157703  0.12560016  0.5089255   1.90058482 -0.79150236 -0.13104951
  -0.58970755  1.39143682  1.42799139  0.20394629]]
[[-0.29743558 -0.49440199  1.49821615 -3.44966412  2.02161336  1.84446955
   3.0917356  -0.92596197  2.00509334 -2.20358992]
 

#  InteractiveSession makes itself the default session

In [51]:
sess = tf.InteractiveSession()
a = tf.constant(5.0)
b = tf.constant(6.0)
c = a * b
print c.eval()
sess.close()

30.0


# Placeholder

In [52]:
# create a placeholder of type float 32-bit, shape is a vector of 3 elements
a = tf.placeholder(tf.float32, shape=[3])
# create a constant of type float 32-bit, shape is a vector of 3 elements
b = tf.constant([5, 5, 5], tf.float32)
# use the placeholder as you would a constant or a variable
c = a + b # Short for tf.add(a, b)
with tf.Session() as sess:
    #print sess.run(c) # Error because a doesn’t have any value
    print sess.run(c, {a:[1,2,3]})

[ 6.  7.  8.]


# Feeding values to TF ops 

In [53]:
a = tf.add(2, 5)
b = tf.multiply(a, 3)
with tf.Session() as sess:
    replace_dict = {a: 15}
    print sess.run(b, feed_dict=replace_dict)

45


# Lazy loading example

In [54]:
#Normal loading example
x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')
z = tf.add(x, y)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    write = tf.summary.FileWriter('/tmp/my_graph/12', sess.graph)
    for _ in range(10):
        sess.run(z)
    write.close()
    
#Lazy loading example
x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    write = tf.summary.FileWriter('/tmp/my_graph/12', sess.graph)
    for _ in range(10):
        sess.run(tf.add(x, y))
    write.close()

# when load graph, add operation will be added many times